<?php
/* 
 * Oferapp < http://www.netyul.com.br/ >.
 * Autor: Jefte Amorim da Costa
 * aquivo que contem o Rodape ultilizadas no sistema Oferapp.
 * versão 1.0
 */	
$pagina = isset( $urlAmigavel[0]) ? $urlAmigavel[0] : '';	
if($pagina == 'login'){
	
}
else{
?>
<!-- Arquivo Footer -->
<footer>
	<div class="container">
    	<div class="row">
        	<div class="col-lg-4">
            	<h4 class="page-header">Sobre</h4>
                <ul>
                	<li><a href="<?php baseurl('contato'); ?>">Contate-nos</a></li>
                    <li><a href="#termos-de-uso" data-toggle="modal">Termos de uso</a></li>
                    <li><a href="<?php baseurl('politica-de-privacidade'); ?>">Política de privacidade</a></li>
                </ul>
            </div>
            <div class="col-lg-4">
            	<h4 class="page-header">Siganos-nos</h4>
                
                <ul class="social">
                	<li><a href="https://www.facebook.com/oferapp.com.br" target="new"><img src="<?php baseurl('skin/images/icon-social-fb.png');?>" ></a> <a href="https://twitter.com/OferAppOficial" target="new"><img src="<?php baseurl('skin/images/icon-social-twitter.png');?>" ></a>
                    <a href="http://gplus.to/OferApp" target="new"><img src="<?php baseurl('skin/images/icon-social-googleplus.png');?>"></a></li>
                </ul>
                
            </div>
            <div class="col-lg-4">
            	<h4 class="page-header">Parceiros</h4>
                <ul class="parceiros">
                	<li><a href="#cadastrarParceiro" data-toggle="modal">Seja um parceiro OferApp</a></li>
                </ul>
            </div>
        </div>
        <div class="footer">
        	
        </div>
    </div>
</footer>  
<?php
}
require_once('skin/termos-popup.php');
?>
</body>
</html>