<!-- Arquivo main -->
<?php 
/* 
 * Oferapp < http://www.netyul.com.br/ >.
 * Autor: Jefte Amorim da Costa
 * aquivo que contem as funções de urlamigavel mais ultilizadas no sistema Oferapp.
 * versão 1.0
 */		
	
		$query_lojista = "SELECT * FROM lojista  ORDER BY id DESC";
		$Result_lojista = mysqli_query($dboferapp, $query_lojista);
		while($rows_lojista = mysqli_fetch_array($Result_lojista)){
			$lojista = str_replace(" ","-", $rows_lojista['nomeFantasia']);
			if($pagina == $lojista){
				$perfilLojista = $lojista;
			}
		}
			
			
		
		
		$paginas = array('contato', 'quem-somos','busca', 'negocios', 'usuario', 'cadastro', 'ofertas', 'tabloides','presentes','logout', 'acessorestrito','login', 'politica-de-privacidade','termos-de-uso');
		//comparar com banco de dados
		
		$query_perfil = "";
		
		if(isset($pagina) && isset($catCidade) && $pagina == $catCidade){
				require_once('paginas/cidade.php');
			}
		//paginas home
		elseif(!isset($pagina) || $pagina ==''){
			require_once('paginas/home.php');
		}
		//paginas fixas
		elseif(isset($pagina) && in_array($pagina, $paginas)){
			require_once('paginas/'. $pagina .'.php');
		}
		//paginas de ação final
		/*elseif(isset($acao) && $acao !=''){
			require_once('paginas/action.php');
		}*/
		//pagina de categorias
		/*elseif(isset($pagina) && !in_array($pagina, $paginas) && $pagina != $catCidade){
			require_once('paginas/categorias.php');
		}*/
		
		//pagina de perfil do lojista
		elseif(isset($pagina) && isset($perfilLojista) && $pagina == $perfilLojista){
				require_once('paginas/perfilLojista.php');
			}
		//pagina de erro
		else{
			require_once('paginas/erro-404.php');
		}
?>
